name = "balancing"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[routes]]
pattern = "api.domain.com/*"
zone_name = "domain.com"

[[triggers]]
crons = ["*/1 * * * *"]

[env.production]
name = "proxy-worker"

[env.development]
name = "proxy-worker-dev"


[vars]
ENVIRONMENT = "production"
HEALTH_CHECK_INTERVAL = "30000"
CIRCUIT_BREAKER_THRESHOLD = "5"

[env.development.vars]
ENVIRONMENT = "development"
HEALTH_CHECK_INTERVAL = "15000"
CIRCUIT_BREAKER_THRESHOLD = "3"

[observability.logs]
enabled = true
